/* tslint:disable */
/* eslint-disable */
/**
 * Scribbletune MIDI Store
 * Store and retrieve MIDI clips via Valkey
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SaveClipResponseDto,
} from '../models/index';
import {
    SaveClipResponseDtoFromJSON,
    SaveClipResponseDtoToJSON,
} from '../models/index';

export interface ClipsControllerDeleteRequest {
    id: string;
}

export interface ClipsControllerFetchRequest {
    id: string;
}

export interface ClipsControllerSaveRequest {
    file: Blob;
}

/**
 * ClipsApi - interface
 * 
 * @export
 * @interface ClipsApiInterface
 */
export interface ClipsApiInterface {
    /**
     * 
     * @summary Delete a MIDI clip
     * @param {string} id Clip UUID returned from POST /clips
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClipsApiInterface
     */
    clipsControllerDeleteRaw(requestParameters: ClipsControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a MIDI clip
     */
    clipsControllerDelete(requestParameters: ClipsControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Download a MIDI clip
     * @param {string} id Clip UUID returned from POST /clips
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClipsApiInterface
     */
    clipsControllerFetchRaw(requestParameters: ClipsControllerFetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Download a MIDI clip
     */
    clipsControllerFetch(requestParameters: ClipsControllerFetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Store a MIDI clip
     * @param {Blob} file MIDI binary file
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClipsApiInterface
     */
    clipsControllerSaveRaw(requestParameters: ClipsControllerSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveClipResponseDto>>;

    /**
     * Store a MIDI clip
     */
    clipsControllerSave(requestParameters: ClipsControllerSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveClipResponseDto>;

}

/**
 * 
 */
export class ClipsApi extends runtime.BaseAPI implements ClipsApiInterface {

    /**
     * Delete a MIDI clip
     */
    async clipsControllerDeleteRaw(requestParameters: ClipsControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clipsControllerDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/clips/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a MIDI clip
     */
    async clipsControllerDelete(requestParameters: ClipsControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clipsControllerDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Download a MIDI clip
     */
    async clipsControllerFetchRaw(requestParameters: ClipsControllerFetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clipsControllerFetch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/clips/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download a MIDI clip
     */
    async clipsControllerFetch(requestParameters: ClipsControllerFetchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clipsControllerFetchRaw(requestParameters, initOverrides);
    }

    /**
     * Store a MIDI clip
     */
    async clipsControllerSaveRaw(requestParameters: ClipsControllerSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveClipResponseDto>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling clipsControllerSave().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/clips`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveClipResponseDtoFromJSON(jsonValue));
    }

    /**
     * Store a MIDI clip
     */
    async clipsControllerSave(requestParameters: ClipsControllerSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveClipResponseDto> {
        const response = await this.clipsControllerSaveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
