/* tslint:disable */
/* eslint-disable */
/**
 * Scribbletune MIDI Store
 * Store and retrieve MIDI clips via Valkey
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveClipResponseDto
 */
export interface SaveClipResponseDto {
    /**
     * Unique clip key, e.g. clips:<uuid>
     * @type {string}
     * @memberof SaveClipResponseDto
     */
    key: string;
    /**
     * Full URL to download the MIDI file
     * @type {string}
     * @memberof SaveClipResponseDto
     */
    downloadUrl: string;
    /**
     * Seconds until the clip expires
     * @type {number}
     * @memberof SaveClipResponseDto
     */
    ttlSeconds: number;
}

/**
 * Check if a given object implements the SaveClipResponseDto interface.
 */
export function instanceOfSaveClipResponseDto(value: object): value is SaveClipResponseDto {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    if (!('ttlSeconds' in value) || value['ttlSeconds'] === undefined) return false;
    return true;
}

export function SaveClipResponseDtoFromJSON(json: any): SaveClipResponseDto {
    return SaveClipResponseDtoFromJSONTyped(json, false);
}

export function SaveClipResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveClipResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'downloadUrl': json['downloadUrl'],
        'ttlSeconds': json['ttlSeconds'],
    };
}

export function SaveClipResponseDtoToJSON(json: any): SaveClipResponseDto {
    return SaveClipResponseDtoToJSONTyped(json, false);
}

export function SaveClipResponseDtoToJSONTyped(value?: SaveClipResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'downloadUrl': value['downloadUrl'],
        'ttlSeconds': value['ttlSeconds'],
    };
}

